### ISSUE TITLE
Does this lib only decode QR codes?

### ISSUE THREAD

**Issue by mairh** [schmich/instascan#59]
Scanning QR code works fine. I was wondering if this library supports decoding any other barcode formats. I am particularly interested in decoding Data Matrix codes.

Is there any way I can modify the core code to decode datamatrix instead?

**Comment by schmich** [comment]
Sorry for the delay in responding. At the moment, the library does not officially support anything other than QR codes, though supporting multiple formats and multiple codes in the same frame is a longer-term goal.

The core of the library is a bit of a Frankenstein. It's powered by the [Emscripten JavaScript build](https://github.com/kig/zxing-cpp-emscripten) of the [C++ port](https://github.com/glassechidna/zxing-cpp) of the [ZXing Java library](https://github.com/zxing/zxing).

If you look at the [Emscripten example](https://github.com/kig/zxing-cpp-emscripten#zxing-emscripten-build), you'll see they make calls to `ZXing._decode_qr` (which this library uses) as well as `ZXing._decode_any`. Since [ZXing supports Data Matrix](https://github.com/zxing/zxing#supported-formats), I believe `ZXing._decode_any` will recognize QR codes, barcodes, Data Matrix, Aztec, etc.

The relevant call is in [scanner.js](https://github.com/schmich/instascan/blob/master/src/scanner.js#L145). Unfortunately, I don't have the time to test it, but the change is small if you'd like to try.

**Comment by mairh** [comment]
Alright. I'll try it out and let you know.

On side related note: Do you have any idea why the demo website stopped working? I am getting the error `Error: Cannot access video stream (DevicesNotFoundError).` on all browsers

<img width="1680" alt="screen shot 2017-07-18 at 14 27 16" src="https://user-images.githubusercontent.com/4072250/28314989-66bd0c60-6bc5-11e7-8251-d341a415b5a2.png">

**Comment by schmich** [comment]
Perhaps you have camera access blocked by default or you blocked access for the demo site sometime in the past?

You should see this prompt when first visiting the demo site:

![screen shot 2017-07-18 at 7 02 49 am](https://user-images.githubusercontent.com/1562839/28316145-3933f710-6b87-11e7-9f42-01da6e67202d.png)

Camera access should be allowed:

![screen shot 2017-07-18 at 7 04 24 am](https://user-images.githubusercontent.com/1562839/28316188-63e7551a-6b87-11e7-9968-169023b77482.png)

**Comment by mairh** [comment]
Closing the issue since all formats are supported when replacing `ZXing._decode_qr` with `ZXing._decode_any` at line https://github.com/schmich/instascan/blob/master/src/scanner.js#L145

Thanks for your help.

**Comment by schmich** [comment]
Thanks for testing this and reporting back. I'm hesitant to officially support other formats right now since I haven't tested them all myself, but again, I definitely want to support them in the future. For now, I created #61 to track this. Thanks again.

**Comment by eggyyy** [comment]
Is it also possible that when I use instascan.min.js minified to scan barcodes?
I tried to change `u._decode_qr(this.decodeCallback)` to `u._decode_any(this.decodeCallback)`
QR now still works, but barcode does not.

**Comment by frapa** [comment]
Same here, with `ZXing._decode_any` the QR codes still work, but barcodes throw an error `Runtime.functionPointers[index] is not a function`

**Comment by Velliz** [comment]
I also facing same issues with @eggyyy
